# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: pretty-format-json
      args:
        - "--autofix"
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: [--branch, main]
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: '2.1.6'
    hooks:
      - id: script-must-not-have-extension
      - id: shellcheck
      - id: shfmt
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
-   repo: https://github.com/psf/black
    rev: '22.6.0'
    hooks:
      - id: black
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
