# Generated by Django 3.2.12 on 2022-05-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TitleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=30, unique=True)),
                ("average_rating", models.FloatField(db_index=True)),
                ("num_votes", models.PositiveBigIntegerField()),
                ("primary_title", models.CharField(max_length=100)),
                ("original_title", models.CharField(max_length=100)),
                ("is_adult", models.BooleanField()),
                ("start_year", models.PositiveIntegerField(db_index=True, null=True)),
                ("end_year", models.PositiveIntegerField(null=True)),
                ("runtime_minutes", models.IntegerField(null=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="watch_items", to="movies.Genre"
                    ),
                ),
                (
                    "title_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.titletype",
                    ),
                ),
            ],
        ),
    ]
