# Generated by Django 3.2.12 on 2022-05-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchitem",
            name="end_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watchitem",
            name="is_adult",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="watchitem",
            name="runtime_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
